export const allCategoriesUrl = '/dvdtheque-service/films/genres'
export const rippedOptions = ['rippé', 'non rippé']
export const vuOptions = ['vu', 'non vu']
export const sortByOptions = ['titre asc', 'titre desc', 'realisateur asc', 'realisateur desc', 'acteur asc', 'acteur desc', 'annee asc', 'annee desc','dateSortieDvd asc','dateSortieDvd desc']
export const DVD = 'DVD'
export const EN_SALLE = 'EN_SALLE'
export const CANAL_PLUS = 'CANAL_PLUS'
export const GOOGLE_PLAY = 'GOOGLE_PLAY'
export const TV = 'TV'
export const TOUS = 'Tous'
export const paginatedSearch = '/films/paginatedSarch'
export const exportUrl = '/films/export'
export const importUrl = '/films/import'
export const defaultQuery = 'origine:eq:DVD:AND,'
export const defaultSort = '-dateInsertion,+titre'